# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, scotty, split }:

cabal.mkDerivation (self: {
  pname = "haskellcgroups";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  meta = {
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
