# This file was auto-generated by cabal2nix. Please do NOT edit manually!

let
  pkgs = import <nixpkgs> {};
  haskellPackages = pkgs.haskellPackages.override {
    extension = self: super: {
      haskellcgroups = self.callPackage ./. {};
    };
  };
in pkgs.myEnvFun {
     name = haskellPackages.haskellcgroups.name;
     buildInputs = [
       (haskellPackages.ghcWithPackages (hs: ([
         hs.cabalInstall
         hs.hscolour
	 hs.scotty
	 hs.split
       ] ++ hs.haskellcgroups.propagatedNativeBuildInputs)))
     ];
   }   
